# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FiltroPeriodo
                                 A QGIS plugin
 Complemento que filtra una vista en base a un field
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-08-03
        copyright            : (C) 2020 by Cristian Fernando Becerra Yarin
        email                : cferbece@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load FiltroPeriodo class from file FiltroPeriodo.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .filtro_periodo import FiltroPeriodo
    return FiltroPeriodo(iface)
